config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'journeys#index'
  resources :journeys do
    resources :expenses, only: %i[index new create destroy] do
      collection do
        get :balance
      end
    end
    resources :journey_members, only: %i[new create edit update]
    resources :journey_locations, only: %i[index new create destroy] do
      collection do
        post :update_ranking
      end
    end
    resources :journey_dates, only: %i[index new create destroy] do
      collection do
        post :update_ranking
      end
    end
    resources :journey_accommodations, only: %i[index new create destroy]
    resources :journey_activities, only: %i[index new create destroy] do
      collection do
        post :update_ranking
      end
    end
  end
  get 'journeys/:id/summary', to: 'journeys#summary', as: :summary
  get '/test', to: 'journeys#test'
  post '/search', to: 'users#search', as: :users_search
  post '/locations/search', to: 'locations#search', as: :locations_search
  post '/activities/search', to: 'activities#search', as: :activities_search
  get '/journeys/:id/has_voted', to: 'journeys#has_voted', as: :has_voted
  get '/journeys/:id/waitings', to: 'journeys#waitings', as: :waitings
  get '/journeys/:id/waitings_act', to: 'journeys#waitings_act', as: :waitings_act
  get '/journeys/:id/journey_locations/votes', to: 'journey_locations#votes', as: :locations_votes
  get '/journeys/:id/journey_dates/votes', to: 'journey_dates#votes', as: :dates_votes
  get '/journeys/:id/journey_accommodations/votes', to: 'journey_accommodations#votes', as: :accommodations_votes
  get '/journeys/:id/journey_activities/votes', to: 'journey_activities#votes', as: :activities_votes
  get '/journeys/:id/waitings_votes', to: 'journey_activities#waitings_votes', as: :waitings_votes
end

app/models/journey_activity.rb
class JourneyActivity < ApplicationRecord
  belongs_to :journey
  belongs_to :activity

  validates :journey, presence: true
  validates :activity, presence: true
end

app/controllers/journey_activities_controller.rb
class JourneyActivitiesController < ApplicationController
  before_action :set_user, :set_journey, only: [:index, :new, :create]

  def index
    @journey_activities = JourneyActivity.where(journey_id: params[:journey_id])
    @journey_activity = JourneyActivity.new
    @location = @journey.journey_locations.max_by(&:ranking).location
    @activities = @location.activities
    @select_activities = @activities.map { |activity| [activity.name, activity.id] }
  end

  def new
    @journey_activity = JourneyActivity.new
    @activities = Activity.all
    @select_activities = @activities.map { |activity| [activity.name, activity.id] }
  end

  def create
    @journey = Journey.find(params[:journey_id])
    @journey_activity = JourneyActivity.new(journey_activity_params)
    @journey_activity.journey = @journey
    if @journey_activity.save!
      redirect_to journey_journey_activities_path(@journey)
    end
  end

  def destroy
    @journey = Journey.find(params[:journey_id])
    @journey_activity = @journey.journey_activities.find(params[:id])
    @journey_activity.destroy
    redirect_to journey_journey_activities_path(@journey)
  end

  def votes
    @journey_activities = JourneyActivity.where(journey_id: params[:id])
    @journey = Journey.find(params[:id])
  end

  def waitings_votes
    @journey = Journey.find(params[:id])
    @journey_members = @journey.journey_members
    @journey_member = JourneyMember.find_by(user_id: current_user.id, journey_id: params[:id])
    @journey_member.activities_voted!
    @all_good = @journey_members.all? { |member| member.read_attribute_before_type_cast(:status) >= 7 }
    WaitingroomChannel.broadcast_to(
      @journey,
      json: {
        journeyMemberId: @journey_member.id,
        status: @journey_member.read_attribute_before_type_cast(:status),
        allGood: @all_good,
        message: 'Découvrez votre week-end'
      }
    )
  end

  def update_ranking
    @journey = Journey.find(params[:journey_id])
    params[:journey_activities].each do |k, activity|
      journey_activity = JourneyActivity.find(activity[:id])
      journey_activity.ranking += activity[:ranking].to_i
      journey_activity.save!
    end
    redirect_to waitings_votes_path(@journey)
  end

  private

  def journey_activity_params
    params.permit(:journey_id, :activity_id)
  end

  def set_user
    @user = current_user
  end

  def set_journey
    @journey = Journey.find(params[:journey_id])
  end

end

app/helpers/journey_activities_helper.rb
module JourneyActivitiesHelper
end

app/views/journey_activities/_activities_results.html.erb
<% if activities.size > 0 %>
	<div class="w-full rounded-3xl px-6 bg-white border border-great-blue-300 my-4">
		<% activities.each do |activity| %>
			<%= button_to journey_journey_activities_path(@journey, activity_id: activity.id), class: "flex items-center gap-2 py-2", data: { turbo: "false" } do %>
				<img src="<%= activity.image_url %>" class="w-8 h-8 object-cover rounded" />
				<span><%= activity.name %></span>
				<span><%= activity.price %></span>
			<% end %>
		<% end %>
	</div>
<% end %>
 

app/views/journey_activities/_journey_activity_card.html.erb
<% defined?(step) ? step = step : step = "default" %>
<div class="journey-activity-card flex items-stretch shadow-md bg-white w-full rounded-lg overflow-hidden relative">
  <div class="journey-activity-card__image shrink-0">
    <img src="<%= journey_activity.activity.image_url %>" />
  </div>
    
  <div class="journey-activity-card__details flex flex-col justify-center grow px-4 py-2">
    <span><%= journey_activity.activity.name.truncate(56, omission: '...') %></span>
    <span class="details-text"><%= journey_activity.activity.price %></span>
  </div>
  <% if step == "vote" %>
    <div class="journey-activity-card__vote">
      <%= render "shared/drag" %>
    </div>
  <% else %>
    <%= link_to journey_journey_activity_path(@journey, journey_activity), data: {turbo_method: :delete, turbo_confirm: "Êtes-vous sûr·e ?"}, class: "absolute right-2 bottom-2 w-6 h-6" do %>
      <%= render "shared/bin" %>
    <% end %>
  <% end %>
</div>

app/views/journey_activities/_search_form.html.erb
<%= form_with url: activities_search_path, method: :post do |form| %>
  <span class="input-search">
    <%= form.search_field :activities_search, oninput: "this.form.requestSubmit()", placeholder: "Chercher une activité" %>
  </span>
  <%= hidden_field :journey, :id %>
<% end %>
<div id="activities_results">
</div>

app/views/journey_activities/index.html.erb
<div class="pb-24">
  <%= render "shared/breadcrumbs", step: "activity" %>

  <h1 class="text-center">Choix des activités</h1>

  <% if @journey_activities.size > 0 %>
    <div class="flex flex-col gap-4 py-8">
      <% @journey_activities.each do |journey_activity| %>
        <%= render "journey_activity_card", journey_activity: journey_activity %>
      <% end %>
    </div>
  <% end %>

<%# <%= form_with model: [@journey, @journey_activity] do |form| %>
  <%# <%= form.label :activity_id %>
  <%# <%= form.select :activity_id, @select_activities %>
  <%# <%= form.submit "Ajouter une activité", class: "btn secundary" %>
<%# <% end %>

<button id="clickBtn" class="btn secundary mt-8">Ajouter une activité</button>
</div>

<div id="popupContainer">
  <div id="popup">
    <span id="closeBtn">&times;</span>
    <h1 class="text-center mb-8">Recherche une activité</h1>
    <%= render "journey_activities/search_form"%>
  </div>
</div>

<div class="fixed bottom-0 left-0 right-0 w-full p-4 bg-white border-t border-great-blue-300">
  <%= link_to "Valider les activités", waitings_act_path(@journey), class:"btn primary" %>
</div>

app/views/journey_activities/new.html.erb
<h1>Ajout d'une activité</h1>

<%= form_with model: [@journey, @journey_activity] do |form| %>
  <%= form.label :activity_id %>
  <%= form.select :activity_id, @select_activities %>
  <%= form.submit "Ajouter une activité" %>
<% end %>

app/views/journey_activities/votes.html.erb
<%= render "shared/breadcrumbs", step: "vote2" %>

<h1 class="text-center">Vote des activités</h1>

<%= form_with url: update_ranking_journey_journey_activities_path(@journey) do |form| %>
  <ul class="cards-sortable flex flex-col gap-4 py-8">
    <% x = 0 %>
    <% @journey_activities.each do |journey_activity| %>
      <li class="card" data-ranking="<%= @journey_activities.count %>">
        <%= render "journey_activity_card", journey_activity: journey_activity, step: "vote" %>
        <%= hidden_field_tag "journey_activities[#{x}][id]", journey_activity.id %>
        <%= hidden_field_tag "journey_activities[#{x}][ranking]", @journey_activities.count - x, class:"hidden_ranking" %>
      </li>
      <% x += 1 %>
    <% end %>
  </ul>
  <div class="fixed bottom-0 left-0 right-0 w-full p-4 bg-white border-t border-great-blue-300">
    <%= form.submit "Je valide mon vote", data: { turbo: false }, class: "btn primary" %>
  </div>
<% end %>

app/views/journey_activities/waitings_votes.html.erb
<%= render "shared/breadcrumbs", step: "vote2" %>

<div  class="w-full"
      data-controller="waitingroom-subscription"
      data-waitingroom-subscription-journey-id-value="<%= @journey.id %>"
      data-waitingroom-subscription-current-user-id-value="<%= current_user.id %>"
      data-waitingroom-subscription-current-user-status-value="<%= @journey_member.read_attribute_before_type_cast(:status) %>"
      >
  
  <h1 class="text-center">Tout le monde a voté ?</h1>

  <%= render "shared/waiting", step_id: 7 %>

  <div class="fixed bottom-0 left-0 right-0 w-full p-4 bg-white border-t border-great-blue-300">
    <%= link_to summary_path(@journey),
                data: { waitingroom_subscription_target: "button"},
                class: "btn primary #{ 'disabled' unless @all_good }" do %>
      <%= @all_good ? "Découvrez votre week-end" : "En attente de vos amis" %>
    <% end %>
  </div>
</div>