config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'journeys#index'
  resources :journeys do
    resources :expenses, only: %i[index new create destroy] do
      collection do
        get :balance
      end
    end
    resources :journey_members, only: %i[new create edit update]
    resources :journey_locations, only: %i[index new create destroy] do
      collection do
        post :update_ranking
      end
    end
    resources :journey_dates, only: %i[index new create destroy] do
      collection do
        post :update_ranking
      end
    end
    resources :journey_accommodations, only: %i[index new create destroy]
    resources :journey_activities, only: %i[index new create destroy] do
      collection do
        post :update_ranking
      end
    end
  end
  get 'journeys/:id/summary', to: 'journeys#summary', as: :summary
  get '/test', to: 'journeys#test'
  post '/search', to: 'users#search', as: :users_search
  post '/locations/search', to: 'locations#search', as: :locations_search
  post '/activities/search', to: 'activities#search', as: :activities_search
  get '/journeys/:id/has_voted', to: 'journeys#has_voted', as: :has_voted
  get '/journeys/:id/waitings', to: 'journeys#waitings', as: :waitings
  get '/journeys/:id/waitings_act', to: 'journeys#waitings_act', as: :waitings_act
  get '/journeys/:id/journey_locations/votes', to: 'journey_locations#votes', as: :locations_votes
  get '/journeys/:id/journey_dates/votes', to: 'journey_dates#votes', as: :dates_votes
  get '/journeys/:id/journey_accommodations/votes', to: 'journey_accommodations#votes', as: :accommodations_votes
  get '/journeys/:id/journey_activities/votes', to: 'journey_activities#votes', as: :activities_votes
  get '/journeys/:id/waitings_votes', to: 'journey_activities#waitings_votes', as: :waitings_votes
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
  validates :name, presence: true
  validates :details, presence: true
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :journey_activities, dependent: :destroy
  has_many :journey, through: :journey_activities
  belongs_to :location

  validates :name, presence: true
  validates :duration_in_h, presence: true
  validates :details, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :journey, required: false
  validates :title, presence: true
  validates :amount, presence: true
  validates :payer, presence: true
  validates :recipient, presence: true
end

app/models/journey.rb
class Journey < ApplicationRecord
  has_many :journey_members, dependent: :destroy
  has_many :users, through: :journey_members, dependent: :destroy
  has_many :journey_locations, dependent: :destroy
  has_many :locations, through: :journey_locations, dependent: :destroy
  has_many :journey_activities, dependent: :destroy
  has_many :activities, through: :journey_activities
  has_many :expenses
  validates :name, presence: true
end

app/models/journey_accommodation.rb
class JourneyAccommodation < ApplicationRecord
  belongs_to :accommodation
  belongs_to :journey

  validates :accommodation, presence: true
  validates :journey, presence: true
end

app/models/journey_activity.rb
class JourneyActivity < ApplicationRecord
  belongs_to :journey
  belongs_to :activity

  validates :journey, presence: true
  validates :activity, presence: true
end

app/models/journey_date.rb
class JourneyDate < ApplicationRecord
  belongs_to :journey

  validates :start_date, presence: true, comparison: { less_than: :end_date }
  validates :end_date, presence: true
end

app/models/journey_location.rb
class JourneyLocation < ApplicationRecord
  belongs_to :location
  belongs_to :journey
end

app/models/journey_member.rb
class JourneyMember < ApplicationRecord
  belongs_to :user
  belongs_to :journey
  enum status: {
    default: 0,
    budget_defined: 1,
    locations_accepted: 2,
    dates_accepted: 3,
    locations_voted: 4,
    dates_voted: 5,
    activities_accepted: 6,
    activities_voted: 7
  }
  # validates :budget, numericality: { only_integer: true }

  def current_status_enum
    read_attribute_before_type_cast(:status)
  end
end

app/models/location.rb
class Location < ApplicationRecord
  validates :country, :city, presence: true
  has_many :journey_locations, dependent: :destroy
  has_many :activities, dependent: :destroy
  # geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?

  def get_rand_image

    url = "https://www.bing.com/images/search?q=#{self.city}&qft=+filterui:imagesize-wallpaper+filterui:photo-photo&form=IRFLTR&first=1&tsc=ImageHoverTitle"
    html = URI.open(url)
    doc = Nokogiri::HTML(html)
    img = doc.css("img").select { |link| link["src"].nil? == false && link["src"].include?("https://") }.map { |link| link["src"] }.first
    img.gsub!("w=", "")
    img.gsub!("h=", "")
  end
end

app/models/location_accommodation.rb
class LocationAccommodation < ApplicationRecord
  belongs_to :location
  belongs_to :accommodation

  validates :location, presence: true
  validates :accommodation, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :journey_members, dependent: :destroy
  has_many :journeys, through: :journey_members, dependent: :destroy
  has_one_attached :avatar
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true, uniqueness: true
end

app/controllers/journey_locations_controller.rb
class JourneyLocationsController < ApplicationController

  def index
    @journey_locations = JourneyLocation.where(journey_id: params[:journey_id])
    @journey = Journey.find(params[:journey_id])
    @journey_members = @journey.journey_members
    @journey_total_budget = 0
    @journey.journey_members.each { |member| @journey_total_budget += member.budget unless member.budget.nil? }

    @journey_location = JourneyLocation.new
    @locations = Location.all
    @select_locations = @locations.map { |location| [location.city, location.id] }
  end

  def new
    @journey_location = JourneyLocation.new
    @journey = Journey.find(params[:journey_id])
    @locations = Location.all
    @select_locations = @locations.map { |location| [location.city, location.id] }
  end

  def create
    @journey_location = JourneyLocation.new(journey_location_params)
    @journey = Journey.find(params[:journey_id])
    if @journey_location.save!
      redirect_to journey_journey_locations_path(@journey)
    end
  end

  def destroy
    @journey = Journey.find(params[:journey_id])
    @journey_location = @journey.journey_locations.find(params[:id])
    @journey_location.destroy
    redirect_to journey_journey_locations_path(@journey)
  end

  def votes
    @journey_locations = JourneyLocation.where(journey_id: params[:id])
    @journey = Journey.find(params[:id])
  end

  def update_ranking
    @journey = Journey.find(params[:journey_id])
    params[:journey_locations].each do |k, location|
      journey_location = JourneyLocation.find(location[:id])
      journey_location.ranking += location[:ranking].to_i
      journey_location.save!
    end
    redirect_to dates_votes_path(@journey)
  end

  private

  def journey_location_params
    params.permit(:location_id, :journey_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.All
  end

  def search
    @journey = Journey.find(params[:journey][:id].to_i)

    if params[:nickname_search].present?
      @users = User.where('nickname ILIKE ?', "%#{params[:nickname_search]}%").order(created_at: :desc)
    else
      @users = User.none
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update('search_results',
          partial: 'users/search_results',
          locals: { users: @users, journey: @journey })
        ]
      end
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/journey_dates_helper.rb
module JourneyDatesHelper
end

app/helpers/journey_locations_helper.rb
module JourneyLocationsHelper
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/journey_locations/_journey_location_card.html.erb
<% defined?(step) ? step = step : step = "default" %>
<div class="journey-location-card flex items-stretch shadow-md bg-white w-full gap-4 rounded-lg overflow-hidden relative">
  <div class="journey-location-card__image shrink-0">
    <img src="<%= journey_location.location.image_url %>" />
  </div>
  <div class="journey-location-card__details flex flex-col justify-center grow">
    <h2><%= journey_location.location.city%></h2>
    <div class="flex items-center gap-2">
      <%= render "shared/location" %>
      <span class="text-great-blue-300">
        <%= journey_location.location.country %>, <%= journey_location.location.zip_code.split('-').first %>
      </span>
    </div>
  </div>
  <% if step == "vote" %>
    <div class="journey-location-card__vote">
      <%= render "shared/drag" %>
    </div>
  <% else %>
    <%= link_to journey_journey_location_path(@journey, journey_location), data: {turbo_method: :delete, turbo_confirm: "Êtes-vous sûr·e ?"}, class: "absolute right-2 bottom-2 w-6 h-6" do %>
      <%= render "shared/bin" %>
    <% end %>
  <% end %>
</div>

app/views/journey_locations/_search_form.html.erb
<%= form_with url: locations_search_path, method: :post do |form| %>
  <span class="input-search">
    <%= form.search_field :locations_search, oninput: "this.form.requestSubmit()", placeholder: "Entrez une ville" %>
  </span>
  <%= hidden_field :journey, :id %>
<% end %>
<div id="locations_results">
</div>

app/views/journey_locations/_search_results.html.erb
<% if locations.size > 0 %>
	<div class="w-full rounded-3xl px-6 bg-white border border-great-blue-300 my-4">
		<% locations.each do |location| %>
			<%= button_to journey_journey_locations_path(@journey, location_id: location.id), class: "flex items-center gap-2 py-2", data: { turbo: "false" } do %>
				<img src="<%= location.image_url %>" class="w-8 h-8 object-cover rounded" />
				<span><%= location.city %></span>
				<span class="text-great-blue-300"><%= location.zip_code.split('-').first %></span>
			<% end %>
		<% end %>
	</div>
<% end %>
 

app/views/journey_locations/index.html.erb
<div class="pb-24">
  <%= render "shared/breadcrumbs", step: "location" %>

  <h1 class="text-center">Choix d'une destination</h1>

  <% if @journey_locations.size > 0 %>
    <div class="flex flex-col gap-4 py-8">
      <% @journey_locations.each do |journey_location| %>
        <%= render "journey_location_card", journey_location: journey_location %>
      <% end %>
    </div>
  <% end %>

  <button id="clickBtn" class="btn secundary mt-8">Ajouter une destination</button>
</div>

<div id="popupContainer">
  <div id="popup">
    <span id="closeBtn">&times;</span>
    <h1 class="text-center mb-8">Recherche par ville</h1>
    <%= render "journey_locations/search_form"%>
  </div>
</div>

<div class="fixed bottom-0 left-0 right-0 w-full p-4 bg-white border-t border-great-blue-300">
  <%= link_to "Je valide ces destinations", journey_journey_dates_path(@journey), class:"btn primary" %>
</div>

app/views/journey_locations/new.html.erb
<h1>Ajout d'un lieu</h1>

<%= form_with model: [@journey, @journey_location] do |form| %>
  <%= form.label :location_id %>
  <%= form.select :location_id, @select_locations %>
  <%= form.submit "Ajouter une ville" %>
<% end %>

app/views/journey_locations/votes.html.erb
<%= render "shared/breadcrumbs", step: "vote1" %>

<h1 class="text-center">Vote de la destination</h1>

<%= form_with url: update_ranking_journey_journey_locations_path(@journey) do |form| %>
  <ul class= "cards-sortable flex flex-col gap-4 py-8">
    <% x = 0 %>
    <% @journey_locations.each do |location| %>
      <li class="card" data-ranking="<%= @journey_locations.count %>">
        <%= render "journey_location_card", journey_location: location, step: "vote" %>
        <%= hidden_field_tag "journey_locations[#{x}][id]", location.id %>
        <%= hidden_field_tag "journey_locations[#{x}][ranking]", @journey_locations.count - x, class:"hidden_ranking" %>
      </li>
      <% x+=1 %>
    <% end %>
  </ul>
  <div class="fixed bottom-0 left-0 right-0 w-full p-4 bg-white border-t border-great-blue-300">
    <%= form.submit "Je valide mon vote", data: { turbo: false }, class: "btn primary" %>
  </div>
<% end %>