config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'journeys#index'
  resources :journeys do
    resources :expenses, only: %i[index new create destroy] do
      collection do
        get :balance
      end
    end
    resources :journey_members, only: %i[new create edit update]
    resources :journey_locations, only: %i[index new create destroy] do
      collection do
        post :update_ranking
      end
    end
    resources :journey_dates, only: %i[index new create destroy] do
      collection do
        post :update_ranking
      end
    end
    resources :journey_accommodations, only: %i[index new create destroy]
    resources :journey_activities, only: %i[index new create destroy] do
      collection do
        post :update_ranking
      end
    end
  end
  get 'journeys/:id/summary', to: 'journeys#summary', as: :summary
  get '/test', to: 'journeys#test'
  post '/search', to: 'users#search', as: :users_search
  post '/locations/search', to: 'locations#search', as: :locations_search
  post '/activities/search', to: 'activities#search', as: :activities_search
  get '/journeys/:id/has_voted', to: 'journeys#has_voted', as: :has_voted
  get '/journeys/:id/waitings', to: 'journeys#waitings', as: :waitings
  get '/journeys/:id/waitings_act', to: 'journeys#waitings_act', as: :waitings_act
  get '/journeys/:id/journey_locations/votes', to: 'journey_locations#votes', as: :locations_votes
  get '/journeys/:id/journey_dates/votes', to: 'journey_dates#votes', as: :dates_votes
  get '/journeys/:id/journey_accommodations/votes', to: 'journey_accommodations#votes', as: :accommodations_votes
  get '/journeys/:id/journey_activities/votes', to: 'journey_activities#votes', as: :activities_votes
  get '/journeys/:id/waitings_votes', to: 'journey_activities#waitings_votes', as: :waitings_votes
end

app/models/journey.rb
class Journey < ApplicationRecord
  has_many :journey_members, dependent: :destroy
  has_many :users, through: :journey_members, dependent: :destroy
  has_many :journey_locations, dependent: :destroy
  has_many :locations, through: :journey_locations, dependent: :destroy
  has_many :journey_activities, dependent: :destroy
  has_many :activities, through: :journey_activities
  has_many :expenses
  validates :name, presence: true
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :test]

  def index
    if current_user
      @journeys = current_user.journeys.order(created_at: :desc)
    end
    @cities_voted = []
    unless @journeys.nil?
      @journeys.each do |journey|
        unless @cities_voted.nil?
          if journey.journey_locations.count > 0
            @city_voted = journey.journey_locations.sort_by { |journey_location| journey_location.ranking }.last.location
            @cities_voted << @city_voted
            @count = journey.journey_members.count
            @name = journey.name
            @journey_dates = JourneyDate.where(journey_id: journey.id)
            @date_voted = @journey_dates.sort_by { |journey_date| journey_date.ranking }.last
          end
        end
        @markers = @cities_voted.map do |city|
          {
            lat: city.latitude,
            lng: city.longitude,
            info_window: render_to_string(partial: 'info_window', locals: { city: city })
          }
        end
      end
    end
  end

  def new
    @journey = Journey.new
  end

  def create
    @journey = Journey.new(journey_params)
    if @journey.save!
      @journey_member = JourneyMember.new(user_id: current_user.id, journey_id: @journey.id)
      if @journey_member.save!
        redirect_to new_journey_journey_member_path(@journey)
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def summary
    @journey = Journey.find(params[:id])
    @journey_locations = JourneyLocation.where(journey_id: @journey.id)
    @journey_dates = JourneyDate.where(journey_id: @journey.id)
    @journey_activities = JourneyActivity.where(journey_id: @journey.id)
    @journey_members = @journey.journey_members
    @journey_total_budget = 0
    @journey.journey_members.each { |member| @journey_total_budget += member.budget unless member.budget.nil? }
    @city_voted = @journey_locations.sort_by { |journey_location| journey_location.ranking }.last
    @date_voted = @journey_dates.sort_by { |journey_date| journey_date.ranking }.last
    @activities = JourneyActivity.where(journey_id: @journey.id)
    @activities_sorted = @journey_activities.sort_by { |activity| activity.ranking }.reverse
    @activity_voted = @journey_activities.sort_by { |activity| activity.ranking }.last
    @journey_member = JourneyMember.find_by(user_id: current_user.id, journey_id: params[:id])
    @journey_member.activities_voted!
  end

  def waitings
    @journey = Journey.find(params[:id])
    @journey_members = @journey.journey_members
    @journey_member = JourneyMember.find_by(user_id: current_user.id, journey_id: params[:id])
    @journey_member.dates_accepted!
    @all_good = @journey_members.all? { |member| member.read_attribute_before_type_cast(:status) >= 3 }
    WaitingroomChannel.broadcast_to(
      @journey,
      json: {
        journeyMemberId: @journey_member.id,
        status: @journey_member.read_attribute_before_type_cast(:status),
        allGood: @all_good,
        message: 'Place aux votes !'
      }
    )
  end

  def waitings_act
    @journey = Journey.find(params[:id])
    @journey_members = @journey.journey_members
    @journey_member = JourneyMember.find_by(user_id: current_user.id, journey_id: params[:id])
    @journey_member.activities_accepted!
    @all_good = @journey_members.all? { |member| member.read_attribute_before_type_cast(:status) >= 6 }
    WaitingroomChannel.broadcast_to(
      @journey,
      json: {
        journeyMemberId: @journey_member.id,
        status: @journey_member.read_attribute_before_type_cast(:status),
        allGood: @all_good,
        message: 'Place aux votes !'
      }
    )
  end

  def has_voted
    @journey = Journey.find(params[:id])
    @journey_members = @journey.journey_members
    @journey_member = JourneyMember.find_by(user_id: current_user.id, journey_id: params[:id])
    @journey_locations = JourneyLocation.where(journey_id: @journey.id)
    @journey_dates = JourneyDate.where(journey_id: @journey.id)
    @city_voted = @journey_locations.sort_by { |journey_location| journey_location.ranking }.last
    @date_voted = @journey_dates.sort_by { |journey_date| journey_date.ranking }.last
    @journey_member.dates_voted!
    @all_good = @journey_members.all? { |member| member.read_attribute_before_type_cast(:status) >= 5 }
    WaitingroomChannel.broadcast_to(
      @journey,
      json: {
        journeyMemberId: @journey_member.id,
        status: @journey_member.read_attribute_before_type_cast(:status),
        allGood: @all_good,
        message: 'Place aux activités !',
        infos: {
          city: @city_voted.location.city,
          startDate: @date_voted.start_date.strftime('%d/%m/%Y'),
          endDate: @date_voted.end_date.strftime('%d/%m/%Y'),
          city_url: @city_voted.location.image_url
        }
      }
    )
  end

  private

  def journey_params
    params.require(:journey).permit(:name, :user)
  end
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/views/journeys/_info_window.html.erb
 <% if @date_voted.end_date.strftime("%d/%m/%Y") > Date.today.to_time  %>
    <p><i>A venir</i></p>
  <% else %>
    <p><i>Terminé</i></p>
  <% end %>
<span class="text-tag"><%= city.city.upcase %></span>
<%= image_tag city.image_url, height: 350, width: 400, crop: :fill %>
<div>
  <strong><%= @count %> Voyageurs</strong>
  <p>Nom du week-end : <%= @name %></p>
    <span>Du</span>
    <span><%= @date_voted.start_date.strftime("%d/%m/%Y")%></span>
    <span>au</span>
    <span><%= @date_voted.end_date.strftime("%d/%m/%Y")%></span>
</div>

app/views/journeys/_journey_card.html.erb
<div class="journey-card flex items-stretch shadow-md bg-white w-full gap-4 rounded-xl overflow-hidden">
  <div class="journey-card__content grow p-4 flex flex-col gap-4">
    <div class="content_title flex justify-between items-center pb-2 gap-4 border-b border-great-blue-200">
      <h2><%= journey.name %></h2>
      <object>
        <p><span><%= link_to "Tricount", journey_expenses_path(journey), class:" m-0 bg-white secundary text-great-blue-500 rounded-xl px-4 py-3"%></span></p>
      </object>
    </div>
    <% unless journey.journey_members.size < 1 %>
      <div class="content_members flex">
        <% journey.journey_members.each do |member| %>
          <%= render "users/avatar", user: member.user %>
        <% end %>
      </div>
    <% end %>
    <div class="content_status flex items-center gap-2">
      <%= render "shared/checked" %>
      <span class="font-bold text-great-blue-500"><%= status %></span>
    </div>
  </div>
  <div class="journey-card__button">
    <%= render "shared/arrow" %>
  </div>
</div>

app/views/journeys/_journey_summary_accommodation.html.erb
<a  class="summary-accommodation shadow-md bg-white w-full rounded-lg overflow-hidden flex"
    href="https://www.airbnb.fr/s/<%= @city_voted.location.city.downcase %>/homes?adults=<%= @journey_members.count%>&checkin=<%= @date_voted.start_date.strftime("%Y-%m-%d") %>&checkout=<%= @date_voted.end_date.strftime("%Y-%m-%d") %>"
    target="_blank"
    >
  <div class="summary-accommodation__details grow flex flex-col items-center justify-center">
    <span>Rechercher un logement sur</span>
    <%= render "shared/airbnb" %>
  </div>
  <div class="summary-accommodation__arrow">
    <%= render "shared/arrow" %>
  </div>
</a> 

app/views/journeys/_journey_summary_activities.html.erb
<div class="summary-activities shadow-md bg-white w-full gap-4 rounded-lg overflow-hidden">
  <% @activities_sorted.each_with_index do |activity, i| %>
    <div class="journey-activity-card flex items-stretch bg-white w-full overflow-hidden<% unless i == 0 %> border-t border-great-blue-300<% end %>">
      <div class="journey-activity-card__image shrink-0">
        <img src="<%= activity.activity.image_url %>" />
        <span class="absolute w-7 h-7 rounded-br-lg flex items-center justify-center left-0 top-0 bg-great-blue-500 text-white"><%= i + 1 %></span>
      </div>
      <div class="journey-activity-card__details flex flex-col justify-center grow px-4 py-2">
        <span><%= activity.activity.name.truncate(56, omission: '...') %></span>
        <span class="details-text"><%= activity.activity.price %></span>
      </div>
    </div>
  <% end %>
</div> 

app/views/journeys/_journey_summary_budget.html.erb
<div class="summary-budget shadow-md bg-white w-full gap-4 rounded-lg overflow-hidden flex items-center justify-center p-4">
  <div class="flex items-center shrink-0">
    <%= render "shared/budget" %>
  </div>
  <div class="flex items-center">
    <span>
      Votre budget logement et activités s'élève à 
      <span class="font-bold text-great-blue-500"><%= @journey_total_budget %> €</span>.
    </span>
  </div>
</div>

app/views/journeys/_journey_summary_location.html.erb
<div class="summary-location shadow-md bg-white w-full gap-4 rounded-lg overflow-hidden">
  <div  class="summary-location__location bg-no-repeat bg-cover"
        style="background-image: url('<%= @city_voted.location.image_url %>');"
        >
    <div class="w-full h-52 left-0 top-0 flex items-center justify-center">
      <div class="bg-dark-alpha px-4 rounded text-white text-bold text-2xl"><%= @city_voted.location.city %></div>
    </div>
  </div>
  <div class="summary-location__date flex items-center justify-center gap-2 p-2">
    <span class="text-great-blue-300">du</span>
    <span class="text-great-blue-600 font-bold"><%= @date_voted.start_date.strftime("%d/%m/%Y")%></span>
    <span class="text-great-blue-300">au</span>
    <span class="text-great-blue-600 font-bold"><%= @date_voted.end_date.strftime("%d/%m/%Y")%></span>
  </div>
</div>

app/views/journeys/_journey_summary_members.html.erb
<div class="summary-members shadow-md bg-white w-full gap-4 rounded-lg overflow-hidden flex items-center justify-center flex-wrap p-4">
  <% @journey_members.each do |journey_member| %>
    <%= render "users/avatar", user: journey_member.user %>
  <% end %>
</div>

app/views/journeys/_summary.html.erb
<section class="journey-summary">
  <h2><%= journey.name %></h2>
  <div>
    <span>Budget total :</span> <%= total_budget %>
  </div>
  <div>
    <span>Participants :</span>
    <% journey_members.each do |member| %>
      <%= render "users/avatar", user: member.user %>
      <span><%= member.user.nickname %></span>
    <% end %>
  </div>
</section>

app/views/journeys/has_voted.html.erb
<%= render "shared/breadcrumbs", step: "vote1" %>

<div  class="w-full"
      data-controller="waitingroom-subscription"
      data-waitingroom-subscription-journey-id-value="<%= @journey.id %>"
      data-waitingroom-subscription-current-user-id-value="<%= current_user.id %>"
      data-waitingroom-subscription-current-user-status-value="<%= @journey_member.read_attribute_before_type_cast(:status) %>"
      >
  <h1 class="text-center">Tout le monde a voté ?</h1>

  <%= render "shared/waiting", step_id: 5 %>

  <div id="vote" class="infos pb-24" data-waitingroom-subscription-target="infos">
    <% if @all_good %>
      <h2 class="text-center my-4">Les votes ont parlé !</h2>
      <%= render "journey_summary_location" %>
    <% end %>
  </div>

  <div class="fixed bottom-0 left-0 right-0 w-full p-4 bg-white border-t border-great-blue-300">
    <%= link_to journey_journey_activities_path(@journey),
                data: {turbo: false, waitingroom_subscription_target: "button"},
                class: "btn primary #{ 'disabled' unless @all_good }" do
                %>
      <%= @all_good ? "Place aux activités !" : "En attente de vos amis..." %>
    <% end %>
  </div>
</div>

app/views/journeys/index.html.erb
<% if current_user %>

  <div class="pb-24">
    <h1 class="text-center mb-6">Mes week-ends</h1>
        <div class="map">
          <div style="width: 100%; height: 500px;" class="mb-5"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>">
          </div>
  </div>

  <div class="flex flex-col gap-4 py-8">
      <% @journeys.each do |journey| %>
        <% journey_member_id = JourneyMember.find_by(journey: journey, user: current_user) %>
        <% case journey_member_id.status%>
          <% when "default" %>
            <% status = "Définir mon budget" %>
            <% card_path = edit_journey_journey_member_path(journey.id, journey_member_id) %>
          <% when "budget_defined" %>
            <% status = "Valider les destinations" %>
            <% card_path = journey_journey_locations_path(journey.id) %>
          <% when "locations_accepted" %>
            <% status = "Valider les dates" %>
            <% card_path = journey_journey_dates_path(journey.id) %>
          <% when "dates_accepted" %>
            <% status = "Voter les destinations" %>
            <% card_path = waitings_path(journey.id) %>
          <% when "locations_voted" %>
            <% status = "Voter les dates" %>
            <% card_path = dates_votes_path(journey.id) %>
          <% when "dates_voted" %>
            <% status = "Valider les activités" %>
            <% card_path = has_voted_path(journey.id) %>
          <% when "activities_accepted" %>
            <% status = "Voter les activités" %>
            <% card_path = waitings_act_path(journey.id) %>
          <% when "activities_voted" %>
            <% status = "Voir le résumé" %>
            <% card_path = summary_path(journey.id) %>
        <% end %>
        <%= link_to card_path, class:"m-2", data: { turbo: "false" } do %>
          <%= render "journey_card", journey: journey, journey_member_id: journey_member_id, status: status %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="fixed bottom-0 left-0 right-0 w-full p-4 bg-white border-t border-great-blue-300">
    <%= link_to "Créer un week-end", new_journey_path, class:"btn secundary" %>
  </div>

<% else %>

  <div class="h-full bg-cover bg-center bg-no-repeat flex flex-col justify-between" style="background-image: linear-gradient(180deg, rgba(255,255,255,0.5) 0%, rgba(255,255,255,0) 100%), url(<%= asset_path 'weekzen_bg.jpg' %>);">
    <div class="grow flex items-center justify-center">
      <h1 class="px-8 pb-72 text-center">L'application qui vous aide à organiser vos week-ends entre ami·e·s</h1>
    </div>
    <%= render "shared/footer" %>
  </div>

<% end %>

app/views/journeys/new.html.erb
<h1 class="text-center">Donner un nom au weeekend</h1>

<div class="flex items-center justify-center py-8 icon64">
  <%= render "shared/date" %>
</div>

<%= form_with model: @journey, class: "grow flex flex-col" do |form| %>
  <div class="flex flex-col gap-4 grow pb-24">
    <%= form.text_field :name, placeholder: "Anniversaire de Tom, Cousinades..." %>
  </div>
  <div class="fixed bottom-0 left-0 right-0 w-full p-4 bg-white border-t border-great-blue-300">
    <%= form.submit "Créer un week-end", class: "btn primary" %>
  </div>
<% end %>

app/views/journeys/summary.html.erb
<div class="flex flex-col gap-4">
  <div class="flex items-center justify-center icon64">
    <%= render "shared/summary" %>
  </div>

  <h1 class="text-center">C'est bientôt l'heure du départ !</h1>

  <%= render "journey_summary_location" %>

  <%= render "journey_summary_members" %>

  <%= render "journey_summary_budget" %>

  <h2 class="text-center pt-4">Pensez à votre logement sur place</h2>

  <%= render "journey_summary_accommodation" %>

  <h2 class="text-center pt-4">Vous allez être bien occupé·e·s !</h2>

  <%= render "journey_summary_activities" %>
</div>

app/views/journeys/waitings.html.erb
<%= render "shared/breadcrumbs", step: "vote1" %>

<div  class="w-full"
      data-controller="waitingroom-subscription"
      data-waitingroom-subscription-journey-id-value="<%= @journey.id %>"
      data-waitingroom-subscription-current-user-id-value="<%= current_user.id %>"
      data-waitingroom-subscription-current-user-status-value="<%= @journey_member.read_attribute_before_type_cast(:status) %>"
      >

  <h1 class="text-center">Prêts à voter ?</h1>

  <%= render "shared/waiting", step_id: 3 %>

  <div class="fixed bottom-0 left-0 right-0 w-full p-4 bg-white border-t border-great-blue-300">
    <%= link_to locations_votes_path(@journey),
                data: {turbo: false, waitingroom_subscription_target: "button"},
                class: "btn primary #{ 'disabled' unless @all_good }" do %>
      <%= @all_good ? "Place aux votes !" : "En attente de vos amis" %>
    <% end %>
  </div>
</div>

app/views/journeys/waitings_act.html.erb
<%= render "shared/breadcrumbs", step: "vote2" %>

<div  class="w-full"
      data-controller="waitingroom-subscription"
      data-waitingroom-subscription-journey-id-value="<%= @journey.id %>"
      data-waitingroom-subscription-current-user-id-value="<%= current_user.id %>"
      data-waitingroom-subscription-current-user-status-value="<%= @journey_member.read_attribute_before_type_cast(:status) %>"
      >

  <h1 class="text-center">Prêts à voter ?</h1>

  <%= render "shared/waiting", step_id: 6 %>

  <div class="fixed bottom-0 left-0 right-0 w-full p-4 bg-white border-t border-great-blue-300">
    <%= link_to activities_votes_path(@journey),
              data: {turbo: false, waitingroom_subscription_target: "button"},
              class: "btn primary #{ 'disabled' unless @all_good }" do
              %>
      <%= @all_good ? "Place aux votes !" : "En attente de vos amis" %>
    <% end %>
  </div>
</div>